---
#  NOTE: PPA repositories are added in init.sh
# - name: Add ppa Repository
#   apt_repository: repo='ppa:ondrej/php5'

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - curl
    - vim
    - python-software-properties
    - build-essential
    - ruby-all-dev
    - libsqlite3-dev
    - mysql-client
    - mysql-server
    - python-mysqldb
    - apache2
    - php5
    - php5-cli
    - php5-mysql
    - php5-curl
    - php5-gd
    - php5-sqlite
    - php5-xmlrpc
    - php5-imagick
    - php5-mysql
    - php5-mcrypt
    - php5-xdebug
    - php5-dev
    - libapache2-mod-php5
    - phpmyadmin
    - mongodb
    - php5-mongo

# Mailcatcher
- name: Add Mailcatcher
  gem: name={{ item }} state=present user_install=no
  with_items:
    - mailcatcher
  sudo: yes

- name: Remove mail server packages
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - mailutils
    - postfix
    - sendmail
    - exim4
    - exim4-base
    - exim4-config
    - exim4-daemon-light
  sudo: yes
